# syntax=docker/dockerfile:experimental

FROM node:alpine AS node-builder-ms

WORKDIR /src

ARG npm_config_unsafe_perm=true
# hack for node to build in linux

RUN --mount=type=cache,id=apk,sharing=locked,target=/var/cache/apk ln -vs /var/cache/apk /etc/apk/cache && \
	apk add --update \
	git

RUN --mount=type=cache,id=npm,sharing=locked,target=/root/.npm \
	npm install tslint typescript -g

COPY package-lock.json /src/
COPY package.json /src/

RUN --mount=type=cache,id=npm,sharing=locked,target=/root/.npm \
	npm install --production

FROM node:alpine AS node-ms-storage

EXPOSE 3000
CMD ["npm", "start"]
WORKDIR /app
ENV NODE_ENV=production

RUN chown node /app

USER node

COPY --from=node-builder-ms --chown=node /src/node_modules /app/node_modules
COPY --chown=node package.json /app/package.json
