FROM node:alpine AS node-builder

WORKDIR /src

# ARG npm_config_unsafe_perm=true
# hack for node to build in linux

COPY package-lock.json /src/
COPY package.json /src/

RUN npm install --production
RUN npm run build


FROM node:alpine AS node-storage

EXPOSE 3000
CMD ["npm", "start"]
WORKDIR /app
ENV NODE_ENV=production

RUN chown node /app

USER node

COPY --from=node-builder --chown=node /src/node_modules /app/node_modules
COPY --from=node-builder --chown=node /src/build /app/build
COPY --chown=node package.json /app/package.json
