FROM alpine:3.10 AS php73
# FROM codecasts/alpine-3.9:php-7.3 AS php73

EXPOSE 9000
CMD ["/usr/sbin/php-fpm7", "-F"]
RUN adduser -DHSu 100 nginx -s /sbin/nologin
RUN ln -sv /usr/sbin/php-fpm7 /usr/sbin/php-fpm
WORKDIR /var/www
COPY --from=composer /usr/bin/composer /usr/bin/composer

COPY ./file.conf /etc/php7/conf.d/file.conf
COPY ./file.conf /etc/php7/php-fpm.d/file.conf

RUN apk add --no-cache \
    php7-fpm \
    php7-bcmath \
    php7-calendar \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-exif \
    php7-fileinfo \
    php7-gd \
    php7-gettext \
    php7-iconv \
    php7-intl \
    php7-json \
    php7-mcrypt \
    php7-mysqli \
    php7-opcache \
    php7-pdo_mysql \
    php7-pdo_sqlite \
    php7-phar \
    php7-posix \
    php7-session \
    php7-simplexml \
    php7-soap \
    php7-sockets \
    php7-sqlite3 \
    php7-sysvmsg \
    php7-sysvsem \
    php7-sysvshm \
    php7-tokenizer \
    php7-wddx \
    php7-xml \
    php7-xmlreader \
    php7-xmlwriter \
    php7-xsl \
    php7-zip
